/* Generated By:JavaCC: Do not edit this line. TemplateParserConstants.java */
package org.modelsphere.jack.templates.parsing;

public interface TemplateParserConstants {

    int EOF = 0;
    int SINGLE_LINE_COMMENT = 8;
    int MULTI_LINE_COMMENT = 9;
    int INTEGER_LITERAL = 11;
    int DECIMAL_LITERAL = 12;
    int HEX_LITERAL = 13;
    int OCTAL_LITERAL = 14;
    int FLOATING_POINT_LITERAL = 15;
    int EXPONENT = 16;
    int CHARACTER_LITERAL = 17;
    int STRING_LITERAL = 18;
    int ATTR = 19;
    int BOOLEAN = 20;
    int CDOM = 21;
    int COND = 22;
    int CONN = 23;
    int FUNCTION = 24;
    int GET = 25;
    int GROUP = 26;
    int IDOM = 27;
    int INTEGER = 28;
    int NEW = 29;
    int PLUGIN = 30;
    int SET = 31;
    int STRING = 32;
    int TEMPL = 33;
    int USERCONN = 34;
    int ADD = 35;
    int AND = 36;
    int BOTH = 37;
    int BY = 38;
    int CHILD = 39;
    int CLEAR = 40;
    int COMPUTE = 41;
    int CONTAINS = 42;
    int _DEFAULT = 43;
    int DIGIT_KW = 44;
    int DISPLAY = 45;
    int DIVIDE = 46;
    int DOM = 47;
    int DQUOTE = 48;
    int DUPLICATED = 49;
    int EITHER = 50;
    int ELEMENT = 51;
    int ELSE = 52;
    int EN = 53;
    int ENABLED = 54;
    int EXTERN = 55;
    int FALSE = 56;
    int FILE = 57;
    int FOREACH = 58;
    int FR = 59;
    int FROM = 60;
    int IF = 61;
    int IFONECHILD = 62;
    int IMPORT = 63;
    int IN = 64;
    int INSTANCEOF = 65;
    int LENGTH = 66;
    int LETTER_KW = 67;
    int LIST = 68;
    int LOWER = 69;
    int MULTIPLY = 70;
    int NOT = 71;
    int NULL = 72;
    int NOCASE = 73;
    int ONLYCONTAINS = 74;
    int OR = 75;
    int ORDER = 76;
    int PARM = 77;
    int PER = 78;
    int PREF = 79;
    int PREF1 = 80;
    int QUOTE = 81;
    int RULE = 82;
    int SEP = 83;
    int STARTSWITH = 84;
    int SUBSTRACT = 85;
    int SUF = 86;
    int SUF1 = 87;
    int TO = 88;
    int TOBOOLEAN = 89;
    int TOFLOAT = 90;
    int TOINTEGER = 91;
    int TOSTRING = 92;
    int TRUE = 93;
    int UNDERSCORE = 94;
    int UNIQUE = 95;
    int UPPER = 96;
    int VARIABLE = 97;
    int WHEN = 98;
    int VAR0 = 99;
    int VAR1 = 100;
    int VAR2 = 101;
    int VAR3 = 102;
    int VAR4 = 103;
    int VAR5 = 104;
    int VAR6 = 105;
    int VAR7 = 106;
    int VAR8 = 107;
    int VAR9 = 108;
    int IDENTIFIER = 109;
    int LETTER = 110;
    int DIGIT = 111;

    int DEFAULT = 0;
    int IN_SINGLE_LINE_COMMENT = 1;
    int IN_MULTI_LINE_COMMENT = 2;

    String[] tokenImage = { "<EOF>", "\" \"", "\"\\t\"", "\"\\r\"", "\"\\n\"", "\"\\f\"", "\"//\"",
            "\"/*\"", "<SINGLE_LINE_COMMENT>", "\"*/\"", "<token of kind 10>", "<INTEGER_LITERAL>",
            "<DECIMAL_LITERAL>", "<HEX_LITERAL>", "<OCTAL_LITERAL>", "<FLOATING_POINT_LITERAL>",
            "<EXPONENT>", "<CHARACTER_LITERAL>", "<STRING_LITERAL>", "\"ATTR\"", "\"BOOLEAN\"",
            "\"CDOM\"", "\"COND\"", "\"CONN\"", "\"FUNCTION\"", "\"GET\"", "\"GROUP\"", "\"IDOM\"",
            "\"INTEGER\"", "\"NEW\"", "\"PLUGIN\"", "\"SET\"", "\"STRING\"", "\"TEMPL\"",
            "\"USERCONN\"", "\"ADD\"", "\"AND\"", "\"BOTH\"", "\"BY\"", "\"CHILD\"", "\"CLEAR\"",
            "\"COMPUTE\"", "\"CONTAINS\"", "\"DEFAULT\"", "\"DIGIT\"", "\"DISPLAY\"", "\"DIVIDE\"",
            "\"DOM\"", "\"DQUOTE\"", "\"DUPLICATED\"", "\"EITHER\"", "\"ELEMENT\"", "\"ELSE\"",
            "\"EN\"", "\"ENABLED\"", "\"EXTERN\"", "\"FALSE\"", "\"FILE\"", "\"FOREACH\"",
            "\"FR\"", "\"FROM\"", "\"IF\"", "\"IFONECHILD\"", "\"IMPORT\"", "\"IN\"",
            "\"INSTANCEOF\"", "\"LENGTH\"", "\"LETTER\"", "\"LIST\"", "\"LOWER\"", "\"MULTIPLY\"",
            "\"NOT\"", "\"NULL\"", "\"NOCASE\"", "\"ONLYCONTAINS\"", "\"OR\"", "\"ORDER\"",
            "\"PARM\"", "\"PER\"", "\"PREF\"", "\"PREF1\"", "\"QUOTE\"", "\"RULE\"", "\"SEP\"",
            "\"STARTSWITH\"", "\"SUBSTRACT\"", "\"SUF\"", "\"SUF1\"", "\"TO\"", "\"TOBOOLEAN\"",
            "\"TOFLOAT\"", "\"TOINTEGER\"", "\"TOSTRING\"", "\"TRUE\"", "\"UNDERSCORE\"",
            "\"UNIQUE\"", "\"UPPER\"", "\"VARIABLE\"", "\"WHEN\"", "\"VAR0\"", "\"VAR1\"",
            "\"VAR2\"", "\"VAR3\"", "\"VAR4\"", "\"VAR5\"", "\"VAR6\"", "\"VAR7\"", "\"VAR8\"",
            "\"VAR9\"", "<IDENTIFIER>", "<LETTER>", "<DIGIT>", "\"=\"", "\";\"", "\"(\"", "\",\"",
            "\")\"", "\"+\"", "\"-\"", "\"*\"", "\"/\"", "\">\"", "\"<\"", "\"==\"", };

}
