// 	MySQL 5.0 (USER DEFINED TARGET SYSTEM)
// 	$Date: 07-11-30 10:23 $
//	
//	Built-in Types

NAME=MySQL
VERSION=5.0
TARGET-ID=2000 	// start to 2000 
ROOT-ID=27	// MySQL

// type, logical type (optional)
TYPES
{
BIGINT, LONG INTEGER
BINARY
BIT
BLOB, BLOB
CHAR, CHARACTER
DATE, DATE
DATETIME, DATE TIME
DECIMAL, DECIMAL
DOUBLE, REAL
DOUBLE PRECISION, DOUBLE PRECISION
ENUM
FLOAT, FLOAT
INT, INTEGER
INTEGER, INTEGER
LONGBLOB, BLOB
LONGTEXT, TEXT
MEDIUMBLOB, BLOB
MEDIUMINT, LONG INTEGER
MEDIUMTEXT, TEXT
NUMERIC, NUMERIC
REAL, REAL
SET
SMALLINT, SMALL INTEGER
TEXT, TEXT
TIME, TIME
TIMESTAMP, TIMESTAMP
TINYBLOB, BLOB
TINYINT, SMALL INTEGER
TINYTEXT, TEXT
VARBINARY
VARCHAR, VARIABLE CHARACTER
YEAR, DATE
}

ALIASES
{
BLOB, TEXT
INT, INTEGER
LONGBLOB, LONGTEXT
MEDIUMBLOB, MEDIUMTEXT
NUMERIC, DECIMAL
REAL, DOUBLE
TINYBLOB, TINYTEXT
}